In this Notebook I am going to do the two types of encoding 1.Ordinal Datra Encoding and 2.Label Data encoding.
Ordinal data Encoding:- When we have a a categoraical data in inputs columns which has order like(Low,Medium,High) called ordinal Data.So we transform the column from characters to string using ordinal encoding.
Label encoding:-When we have categorical Data in output feature so we use Label encoding and its just givv it representative values like(0 to A,1 to B,2 to C etc).

Import Numpy and Pandas for working with file

In [178]:
import numpy as np
import pandas as pd

Reading data

In [179]:
column_required=["winner","host_city_final"]

In [180]:
df=pd.read_csv("https://raw.githubusercontent.com/awais-DS/Data/refs/heads/main/FIFA_World_Cup_Champions_1930_2022.csv",usecols=column_required)

In [181]:
df.columns

Index(['host_city_final', 'winner'], dtype='object')

Viewing only Numercal and Categorical Fetures from Data

In [182]:
n_cols=df.select_dtypes(include="number")
n_cols.head()
cat_cols=df.select_dtypes(include=["category","string","object"])

In [183]:
cat_cols.shape

(22, 2)

In [184]:
cat_cols.head()

  host_city_final        winner
0      Montevideo       Uruguay
1            Rome         Italy
2           Paris         Italy
3  Rio de Janeiro       Uruguay
4            Bern  West Germany

In [185]:
df.shape

(22, 2)

In [186]:
type(df)

pandas.core.frame.DataFrame

In [187]:
df["Performance_category"]=["A","B","C","D","C","A","C","A","D","B","A","C","A","B","B","C","A","C","B","A","B","C"]

In [188]:
df = df[df['Performance_category'] != 'E']

In [189]:
df=pd.DataFrame(df)

In [190]:
df.head()

  host_city_final        winner Performance_category
0      Montevideo       Uruguay                    A
1            Rome         Italy                    B
2           Paris         Italy                    C
3  Rio de Janeiro       Uruguay                    D
4            Bern  West Germany                    C

In [191]:
df["host_city_final"].tolist()

['Montevideo',
 'Rome',
 'Paris',
 'Rio de Janeiro',
 'Bern',
 'Solna',
 'Santiago',
 'London',
 'Mexico City',
 'Munich',
 'Buenos Aires',
 'Madrid',
 'Mexico City',
 'Rome',
 'Pasadena',
 'Saint-Denis',
 'Yokohama',
 'Berlin',
 'Johannesburg',
 'Rio de Janeiro',
 'Moscow',
 'Lusail']

In [192]:
from sklearn.preprocessing import OrdinalEncoder

In [193]:
oe=OrdinalEncoder()

In [194]:
x = df[["Performance_category", "host_city_final"]]
y=df["winner"]

In [195]:
from sklearn.model_selection import train_test_split

In [196]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [197]:
x_train

   Performance_category host_city_final
21                    C          Lusail
11                    C          Madrid
19                    A  Rio de Janeiro
8                     D     Mexico City
6                     C        Santiago
16                    A        Yokohama
4                     C            Bern
2                     C           Paris
5                     A           Solna
17                    C          Berlin
9                     B          Munich
7                     A          London
18                    B    Johannesburg
3                     D  Rio de Janeiro
0                     A      Montevideo
15                    C     Saint-Denis
12                    A     Mexico City

In [198]:
oe=OrdinalEncoder(categories=[["E","D","C","B","A"],['Montevideo','Rome','Paris','Rio de Janeiro','Bern','Solna','Santiago','London','Mexico City','Munich','Buenos Aires','Madrid','Pasadena','Saint-Denis','Yokohama','Berlin','Johannesburg','Moscow','Lusail']])

In [199]:
df['Performance_category'].unique()

array(['A', 'B', 'C', 'D'], dtype=object)

In [200]:
x_train_encoded=oe.fit_transform(x_train)

In [201]:
oe.categories_

[array(['E', 'D', 'C', 'B', 'A'], dtype=object),
 array(['Montevideo', 'Rome', 'Paris', 'Rio de Janeiro', 'Bern', 'Solna',
        'Santiago', 'London', 'Mexico City', 'Munich', 'Buenos Aires',
        'Madrid', 'Pasadena', 'Saint-Denis', 'Yokohama', 'Berlin',
        'Johannesburg', 'Moscow', 'Lusail'], dtype=object)]

In [202]:
x_train

   Performance_category host_city_final
21                    C          Lusail
11                    C          Madrid
19                    A  Rio de Janeiro
8                     D     Mexico City
6                     C        Santiago
16                    A        Yokohama
4                     C            Bern
2                     C           Paris
5                     A           Solna
17                    C          Berlin
9                     B          Munich
7                     A          London
18                    B    Johannesburg
3                     D  Rio de Janeiro
0                     A      Montevideo
15                    C     Saint-Denis
12                    A     Mexico City

In [203]:
x_test=oe.transform(x_test)

In [204]:
x_test

array([[ 3., 17.],
       [ 4., 10.],
       [ 3., 12.],
       [ 3.,  1.],
       [ 3.,  1.]])

In [208]:
x_train_encoded=pd.DataFrame(x_train,columns=x_train.columns)

In [209]:
x_train_encoded

   Performance_category host_city_final
21                    C          Lusail
11                    C          Madrid
19                    A  Rio de Janeiro
8                     D     Mexico City
6                     C        Santiago
16                    A        Yokohama
4                     C            Bern
2                     C           Paris
5                     A           Solna
17                    C          Berlin
9                     B          Munich
7                     A          London
18                    B    Johannesburg
3                     D  Rio de Janeiro
0                     A      Montevideo
15                    C     Saint-Denis
12                    A     Mexico City

In [210]:
from sklearn.preprocessing import LabelEncoder

In [211]:
le=LabelEncoder()

In [213]:
y

0          Uruguay
1            Italy
2            Italy
3          Uruguay
4     West Germany
5           Brazil
6           Brazil
7          England
8           Brazil
9     West Germany
10       Argentina
11           Italy
12       Argentina
13    West Germany
14          Brazil
15          France
16          Brazil
17           Italy
18           Spain
19         Germany
20          France
21       Argentina
Name: winner, dtype: object

In [214]:
y_train_le_ecoded=le.fit_transform(y_train)

In [215]:
t_test_le_encoded=le.transform(y_test)

In [216]:
y_train_le_ecoded

array([0, 5, 4, 1, 1, 1, 8, 5, 1, 5, 8, 2, 6, 7, 7, 3, 0])

Encoding Through Column Transformer a Class of Scikitlearn .Which do all the work simply by writing a few lines of code.

In [1]:
print("Hello WOrld")

Hello WOrld

In [3]:
import pandas as pd
import numpy as np

In [6]:
dff=pd.read_csv("https://raw.githubusercontent.com/awais-DS/Data/refs/heads/main/FIFA_World_Cup_Champions_1930_2022.csv")

In [7]:
dff.head()

   year host_country  ... mascot         official_ball
0  1930      Uruguay  ...    NaN               T-Model
1  1934        Italy  ...    NaN          Federale 102
2  1938       France  ...    NaN                 Allen
3  1950       Brazil  ...    NaN         Super Duplo T
4  1954  Switzerland  ...    NaN  Swiss World Champion

[5 rows x 23 columns]

In [ ]:
df_new=dff["year","host_country",""]

In [2]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer